// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Judge.proto
#ifndef GRPC_Judge_2eproto__INCLUDED
#define GRPC_Judge_2eproto__INCLUDED

#include "Judge.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace judge {

class JudgeService final {
 public:
  static constexpr char const* service_full_name() {
    return "judge.JudgeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Judge(::grpc::ClientContext* context, const ::judge::JudgeTask& request, ::judge::JudgeResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::judge::JudgeResult>> AsyncJudge(::grpc::ClientContext* context, const ::judge::JudgeTask& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::judge::JudgeResult>>(AsyncJudgeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::judge::JudgeResult>> PrepareAsyncJudge(::grpc::ClientContext* context, const ::judge::JudgeTask& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::judge::JudgeResult>>(PrepareAsyncJudgeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::judge::JudgeTask, ::judge::JudgeResult>> ProcessJudgeTask(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::judge::JudgeTask, ::judge::JudgeResult>>(ProcessJudgeTaskRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::judge::JudgeTask, ::judge::JudgeResult>> AsyncProcessJudgeTask(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::judge::JudgeTask, ::judge::JudgeResult>>(AsyncProcessJudgeTaskRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::judge::JudgeTask, ::judge::JudgeResult>> PrepareAsyncProcessJudgeTask(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::judge::JudgeTask, ::judge::JudgeResult>>(PrepareAsyncProcessJudgeTaskRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Judge(::grpc::ClientContext* context, const ::judge::JudgeTask* request, ::judge::JudgeResult* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Judge(::grpc::ClientContext* context, const ::judge::JudgeTask* request, ::judge::JudgeResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ProcessJudgeTask(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::judge::JudgeTask,::judge::JudgeResult>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::judge::JudgeResult>* AsyncJudgeRaw(::grpc::ClientContext* context, const ::judge::JudgeTask& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::judge::JudgeResult>* PrepareAsyncJudgeRaw(::grpc::ClientContext* context, const ::judge::JudgeTask& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::judge::JudgeTask, ::judge::JudgeResult>* ProcessJudgeTaskRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::judge::JudgeTask, ::judge::JudgeResult>* AsyncProcessJudgeTaskRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::judge::JudgeTask, ::judge::JudgeResult>* PrepareAsyncProcessJudgeTaskRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Judge(::grpc::ClientContext* context, const ::judge::JudgeTask& request, ::judge::JudgeResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::judge::JudgeResult>> AsyncJudge(::grpc::ClientContext* context, const ::judge::JudgeTask& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::judge::JudgeResult>>(AsyncJudgeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::judge::JudgeResult>> PrepareAsyncJudge(::grpc::ClientContext* context, const ::judge::JudgeTask& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::judge::JudgeResult>>(PrepareAsyncJudgeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::judge::JudgeTask, ::judge::JudgeResult>> ProcessJudgeTask(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::judge::JudgeTask, ::judge::JudgeResult>>(ProcessJudgeTaskRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::judge::JudgeTask, ::judge::JudgeResult>> AsyncProcessJudgeTask(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::judge::JudgeTask, ::judge::JudgeResult>>(AsyncProcessJudgeTaskRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::judge::JudgeTask, ::judge::JudgeResult>> PrepareAsyncProcessJudgeTask(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::judge::JudgeTask, ::judge::JudgeResult>>(PrepareAsyncProcessJudgeTaskRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Judge(::grpc::ClientContext* context, const ::judge::JudgeTask* request, ::judge::JudgeResult* response, std::function<void(::grpc::Status)>) override;
      void Judge(::grpc::ClientContext* context, const ::judge::JudgeTask* request, ::judge::JudgeResult* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ProcessJudgeTask(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::judge::JudgeTask,::judge::JudgeResult>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::judge::JudgeResult>* AsyncJudgeRaw(::grpc::ClientContext* context, const ::judge::JudgeTask& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::judge::JudgeResult>* PrepareAsyncJudgeRaw(::grpc::ClientContext* context, const ::judge::JudgeTask& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::judge::JudgeTask, ::judge::JudgeResult>* ProcessJudgeTaskRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::judge::JudgeTask, ::judge::JudgeResult>* AsyncProcessJudgeTaskRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::judge::JudgeTask, ::judge::JudgeResult>* PrepareAsyncProcessJudgeTaskRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Judge_;
    const ::grpc::internal::RpcMethod rpcmethod_ProcessJudgeTask_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Judge(::grpc::ServerContext* context, const ::judge::JudgeTask* request, ::judge::JudgeResult* response);
    virtual ::grpc::Status ProcessJudgeTask(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::judge::JudgeResult, ::judge::JudgeTask>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Judge() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::judge::JudgeTask* /*request*/, ::judge::JudgeResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJudge(::grpc::ServerContext* context, ::judge::JudgeTask* request, ::grpc::ServerAsyncResponseWriter< ::judge::JudgeResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessJudgeTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProcessJudgeTask() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ProcessJudgeTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessJudgeTask(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::judge::JudgeResult, ::judge::JudgeTask>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessJudgeTask(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::judge::JudgeResult, ::judge::JudgeTask>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Judge<WithAsyncMethod_ProcessJudgeTask<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Judge() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::judge::JudgeTask, ::judge::JudgeResult>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::judge::JudgeTask* request, ::judge::JudgeResult* response) { return this->Judge(context, request, response); }));}
    void SetMessageAllocatorFor_Judge(
        ::grpc::MessageAllocator< ::judge::JudgeTask, ::judge::JudgeResult>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::judge::JudgeTask, ::judge::JudgeResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::judge::JudgeTask* /*request*/, ::judge::JudgeResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Judge(
      ::grpc::CallbackServerContext* /*context*/, const ::judge::JudgeTask* /*request*/, ::judge::JudgeResult* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ProcessJudgeTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ProcessJudgeTask() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::judge::JudgeTask, ::judge::JudgeResult>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ProcessJudgeTask(context); }));
    }
    ~WithCallbackMethod_ProcessJudgeTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessJudgeTask(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::judge::JudgeResult, ::judge::JudgeTask>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::judge::JudgeTask, ::judge::JudgeResult>* ProcessJudgeTask(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_Judge<WithCallbackMethod_ProcessJudgeTask<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Judge() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::judge::JudgeTask* /*request*/, ::judge::JudgeResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ProcessJudgeTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProcessJudgeTask() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ProcessJudgeTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessJudgeTask(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::judge::JudgeResult, ::judge::JudgeTask>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Judge() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::judge::JudgeTask* /*request*/, ::judge::JudgeResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJudge(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProcessJudgeTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProcessJudgeTask() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ProcessJudgeTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessJudgeTask(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::judge::JudgeResult, ::judge::JudgeTask>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessJudgeTask(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Judge() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Judge(context, request, response); }));
    }
    ~WithRawCallbackMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::judge::JudgeTask* /*request*/, ::judge::JudgeResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Judge(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ProcessJudgeTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ProcessJudgeTask() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ProcessJudgeTask(context); }));
    }
    ~WithRawCallbackMethod_ProcessJudgeTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessJudgeTask(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::judge::JudgeResult, ::judge::JudgeTask>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* ProcessJudgeTask(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Judge() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::judge::JudgeTask, ::judge::JudgeResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::judge::JudgeTask, ::judge::JudgeResult>* streamer) {
                       return this->StreamedJudge(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::judge::JudgeTask* /*request*/, ::judge::JudgeResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedJudge(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::judge::JudgeTask,::judge::JudgeResult>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Judge<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Judge<Service > StreamedService;
};

}  // namespace judge


#endif  // GRPC_Judge_2eproto__INCLUDED
